/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AlunoDAO;
import dao.LivrosDAO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author miguel
 */
public class TelaDoAluno extends javax.swing.JFrame {

    /**
     * Creates new form TelaAluno
     */
    public TelaDoAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VisualizarLivrosDisponíveis = new javax.swing.JButton();
        Emprestimo = new javax.swing.JButton();
        Devolver = new javax.swing.JButton();
        RenovarEmprestimo = new javax.swing.JButton();
        LivrosEmprestados = new javax.swing.JButton();
        Retornar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Livros = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Emprestados = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VisualizarLivrosDisponíveis.setText("Visualizar Livros Disponíveis");
        VisualizarLivrosDisponíveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarLivrosDisponíveisActionPerformed(evt);
            }
        });

        Emprestimo.setText("Solicitar Empréstimo");
        Emprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmprestimoActionPerformed(evt);
            }
        });

        Devolver.setText("Devolver Livro");
        Devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevolverActionPerformed(evt);
            }
        });

        RenovarEmprestimo.setText("Renovar Empréstimo");
        RenovarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenovarEmprestimoActionPerformed(evt);
            }
        });

        LivrosEmprestados.setText("Livros Emprestados");
        LivrosEmprestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LivrosEmprestadosActionPerformed(evt);
            }
        });

        Retornar.setText("Retornar");
        Retornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetornarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(Livros);

        jScrollPane2.setViewportView(Emprestados);

        jLabel1.setText("Lista de Livros");

        jLabel2.setText("Lista  de Livros Emprestados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(VisualizarLivrosDisponíveis)
                        .addGap(18, 18, 18)
                        .addComponent(Emprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(108, 108, 108)
                        .addComponent(Retornar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LivrosEmprestados, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RenovarEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Devolver, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 123, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Retornar)
                            .addComponent(jLabel2))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VisualizarLivrosDisponíveis)
                    .addComponent(Emprestimo)
                    .addComponent(LivrosEmprestados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Devolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RenovarEmprestimo)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevolverActionPerformed
        Devolver.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                DefaultListModel listaLivros = new DefaultListModel();
                if(LivrosDAO.retornarTamanhoDaLista() > 0) {
                    LivrosDAO.devolver(Emprestados.getSelectedIndex());
                    
                    JOptionPane.showMessageDialog(null, "Livro devolvido!");
                    
                    for (int c = 0; c < LivrosDAO.retornarTamanhoDaLista(); c++){
                    listaLivros.addElement(LivrosDAO.getLivros(c));
                        
                    }
                }
                Emprestados.setModel(listaLivros);
            }
        
        });
    }//GEN-LAST:event_DevolverActionPerformed

    private void LivrosEmprestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LivrosEmprestadosActionPerformed
        DefaultListModel listaLivros = new DefaultListModel();
        if (LivrosDAO.retornarTamanhoDaLista() > 0){
            for (int k = 0; k < LivrosDAO.retornarTamanhoDaLista(); k++){
                if(LivrosDAO.getLivros(k).isEmprestado() == true){
                    listaLivros.addElement(LivrosDAO.getLivros(k));
                }
            }
        }else{
        listaLivros.addElement("Você não possui livros emprestados!");
        }
        Emprestados.setModel(listaLivros);
    }//GEN-LAST:event_LivrosEmprestadosActionPerformed

    private void RetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornarActionPerformed
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RetornarActionPerformed

    private void VisualizarLivrosDisponíveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarLivrosDisponíveisActionPerformed
        DefaultListModel listaLivros = new DefaultListModel();
        if (LivrosDAO.retornarTamanhoDaLista() > 0){
            for (int k = 0; k < LivrosDAO.retornarTamanhoDaLista(); k++){
                if(LivrosDAO.getLivros(k).isEmprestado() == false){
                    listaLivros.addElement(LivrosDAO.getLivros(k));
                }
            }
        }else{
            listaLivros.addElement("Não existem livros disponíveis!");
        }
        Livros.setModel(listaLivros);
    }//GEN-LAST:event_VisualizarLivrosDisponíveisActionPerformed

    private void EmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmprestimoActionPerformed
        Emprestimo.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                DefaultListModel listaLivros = new DefaultListModel();
                if(LivrosDAO.retornarTamanhoDaLista() > 0) {
                    LivrosDAO.emprestimo(Livros.getSelectedIndex());

                    JOptionPane.showMessageDialog(null, "Empréstimo realizado!");
                    
                    for (int c = 0; c < LivrosDAO.retornarTamanhoDaLista(); c++){
                    listaLivros.addElement(LivrosDAO.getLivros(c));
                        
                    }
                }
                Livros.setModel(listaLivros);
            }
        
        });
    }//GEN-LAST:event_EmprestimoActionPerformed

    private void RenovarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenovarEmprestimoActionPerformed
        RenovarEmprestimo.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                DefaultListModel listaLivros = new DefaultListModel();
                if(LivrosDAO.retornarTamanhoDaLista() > 0) {
                    LivrosDAO.renovarEmprestimo(Emprestados.getSelectedIndex());
                    
                    JOptionPane.showMessageDialog(null, "Empréstimo renovado!");
                    
                    for (int c = 0; c < LivrosDAO.retornarTamanhoDaLista(); c++){
                    listaLivros.addElement(LivrosDAO.getLivros(c));
                        
                    }
                }
                Emprestados.setModel(listaLivros);
            }
        
        });
    }//GEN-LAST:event_RenovarEmprestimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDoAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Devolver;
    private javax.swing.JList<String> Emprestados;
    private javax.swing.JButton Emprestimo;
    private javax.swing.JList<String> Livros;
    private javax.swing.JButton LivrosEmprestados;
    private javax.swing.JButton RenovarEmprestimo;
    private javax.swing.JButton Retornar;
    private javax.swing.JButton VisualizarLivrosDisponíveis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
